### PR TITLE
Fix datetime issue of redis 3.x

### PR DESCRIPTION
**Pull request by Germey**
Fix datetime issue of redis 3.x, otherwise it will raise:

```
redis.exceptions.DataError: Invalid input of type: 'datetime'. Convert to a bytes, string, int or float first.
```

Just change datetime to timestamp

### CODE REVIEW

**Comment by Germey** [comment]
Or do you think we should limit redis version to 2.x?

**Review by rmax — APPROVED** [review]

**Comment by rmax** [comment]
Looks good to me!

**Comment by Germey** [comment]
Wait, I just get a comment for this PR. If I change it to datetime, the final report will be changed:

Before:

```
{'downloader/request_bytes': 2925,
 'downloader/request_count': 11,
 'downloader/request_method_count/GET': 11,
 'downloader/response_bytes': 23406,
 'downloader/response_count': 11,
 'downloader/response_status_count/200': 10,
 'downloader/response_status_count/404': 1,
 'elapsed_time_seconds': 3.917599,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2021, 3, 15, 14, 1, 36, 275427),
 'item_scraped_count': 100,
 'log_count/DEBUG': 111,
 'log_count/INFO': 10,
 'memusage/max': 55242752,
 'memusage/startup': 55242752,
 'request_depth_max': 9,
 'response_received_count': 11,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/404': 1,
 'scheduler/dequeued': 10,
 'scheduler/dequeued/memory': 10,
 'scheduler/enqueued': 10,
 'scheduler/enqueued/memory': 10,
 'start_time': datetime.datetime(2021, 3, 15, 14, 1, 32, 357828)}
2021-03-15 22:01:36 [scrapy.core.engine] INFO: Spider closed (finished)
``` 

After:

```
{'downloader/request_bytes': 2925,
 'downloader/request_count': 11,
 'downloader/request_method_count/GET': 11,
 'downloader/response_bytes': 23406,
 'downloader/response_count': 11,
 'downloader/response_status_count/200': 10,
 'downloader/response_status_count/404': 1,
 'elapsed_time_seconds': 3.917599,
 'finish_reason': 'finished',
 'finish_time': <timestamp>,
 'item_scraped_count': 100,
 'log_count/DEBUG': 111,
 'log_count/INFO': 10,
 'memusage/max': 55242752,
 'memusage/startup': 55242752,
 'request_depth_max': 9,
 'response_received_count': 11,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/404': 1,
 'scheduler/dequeued': 10,
 'scheduler/dequeued/memory': 10,
 'scheduler/enqueued': 10,
 'scheduler/enqueued/memory': 10,
 'start_time': <timestamp>}
2021-03-15 22:01:36 [scrapy.core.engine] INFO: Spider closed (finished)
```

It affects the final report result, do you think it make sense?

This PR is used to fix the issue on redis-py 3.x,  because redis-py 3.x does not allow us to set datetime type as a value. Do you think we should limit redis-py version to 2.x ?

**Comment by Germey** [comment]
Please don't merge it for now, I will do more test and updates on it to ensure it does not influence any behavior of Scrapy.

**Comment by nieweiming** [comment]
redis stats #196

some problem with start_time.

**Pull request closed without merging**
