### PR TITLE
[WIP] Enhance scrapy-redis

### PR DESCRIPTION
**Pull request by whg517**
ref #203 

Task list

- [x] Added GitHub Action workflow
- [x] Add pep-0517 A build-system independent format for source trees support
- [x] Added adaptation from Python 3.7 to Python 3.10, and removed Python 2 support
- [ ] Add Type annotations pep-0483
- [ ] Add pytest to test project
- [ ] Use modern sphinx theme -- furo , like pip document

### CODE REVIEW

**Comment by whg517** [comment]
Thank you for your recognition. If you have any questions, please raise them in time and I will make modifications.

**Comment by LuckyPigeon** [comment]
Seems too many changes in a PR to me.

**Comment by LuckyPigeon** [comment]
@Germey 
Can you help review this?

**Comment by Germey** [comment]
@LuckyPigeon I think there're also too many changes in this PR. @whg517 Could you please split these changes into multiple PRs, every PR for every TODO? 

I don't think this large PR can be accepted.

**Review by LuckyPigeon — CHANGES_REQUESTED** [review]
Please split to each task a PR, thanks!

**Pull request closed without merging**
